### ISSUE TITLE
Review SRS document ((Domain Expert))

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#4]
@gordonwky please review my SRS document.

[SRS](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/SRS/SRS.pdf)

**Comment by gordonwky** [comment]
Is the accuracy <= 90 % a typo in P.7 and P.20, because you state the accuracy should be larger or equal 90% (section 3.1 Accurate Segmentation P.3).

**Comment by lele0007** [comment]
yes, it should be >=90%

**Comment by gordonwky** [comment]
Some comments or question about the SRS 
1. Typo in p.7 and p.20 about accuracy (already clarified)
2. The relation between G1 and (G2 and G3). I think G2 and G3 are more about the application or usability about the software.I think this part should be placed in other section instead of goal statement since G2 and G3 seems not giving some new information on your software output and more or less a consequence of implementing G1.
3. In section of Terminology, you mentioned about the definition of RGB. Is there any layman term for “bitmap” and “channels”. I think this part could have less jargon.
4. You mentioned feature extraction in your model. However, I could not see it explicitly in the section of system context. Could you explain how feature extraction is included in your software with a system context graph? Is this an extra feature beside image fragmentation ? If it is, you could include this into your goal statement.
5. Could I ask for the mathematical structure about the image ? Is it in matrix representation in real number or integer or others? 
6. In terms of high-quality image, is there formal definition for this or properties that it should satisfied.

**Comment by smiths** [comment]
The review has been done, so this issue can be closed.  @lele0007 you may wish to create separate issues so that you can address this feedback.  Regardless of how you do it, you should address the feedback.
