### ISSUE TITLE
Review SRS document ((Secondary Reviewer))

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#5]
@mirzaim  please review my SRS document.

[SRS](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
@mirzaim please review the SRS.

**Comment by mirzaim** [comment]
Hi @lele0007, I really enjoyed your project. Here are all my reviews. I'm not 100% sure that many of them are correct. I've marked the most important one as an issue.

"
In the User’s responsibility section, it mentions that users should maintain patient data confidentiality and provide feedback. However, if they fail to do these things, your system won’t break. Therefore, you could consider removing these responsibilities. I'm uncertain about whether these aspects should be included in the SRS. It's like more privacy policy.

In the software responsibility section, Data Processing is mentioned, which may contradict users’ responsibility for data preparation and upload. It's unclear whether it's the user's responsibility to preprocess the data or your software.

Perhaps the software responsibility section should be more high-level. For instance, you train a model once and integrate it into the software, but users don't need to know about this process. Therefore, you could consider removing this part from the software responsibility section.

Your system constraints regarding hardware limitations are well-defined. However, for aspects like scalability, you may need to be more specific and measurable regarding the level of scalability desired. Additionally, data privacy may not fall under system constraints.

In the Terminology section, for Semantic Segmentation, the definition is limited to deep learning algorithms, whereas other classical methods like threshold methods are not included.

Considering the frequent use of the term "deep learning," it may be beneficial to provide a definition for it in the Terminology section.

In the goal statement section, for GS1, aiming for an accuracy of 90% is mentioned, but it's crucial to specify the dataset and benchmark for evaluation to give meaning to this accuracy. This ensures alignment between you and your stakeholders.

The goal GS2 seems vague and unclear. It would be helpful to clearly define what constitutes achieving these goals.
"
GS2: Enhanced Diagnostic Support: To aid healthcare professionals in the diagnosis and
monitoring of ocular diseases, such as diabetic retinopathy, glaucoma, and age-related
macular degeneration, by offering detailed visualizations of retinal blood vessels. For
each given retinal RGB image input, display the corresponding vessel segmentation
image, i.e., a binary image, the vessel part is represented by white pixels, and the
other parts are represented by black pixels.
"

In the definition of image segmentation, the types of I and S are not mentioned. For example, specifying the type of input as [0, 1]^(WxHx3) and output as {0, 1}^(WxH) would be beneficial. Additionally, instead of "Si union with Sj," considering the intersection of these two could be more appropriate.

The term "filter matrix" mentioned in the “Solution Characteristics Specification” section is not explained elsewhere in the document and it's not clear what is it.

The output segmentation format is unclear and varies between a binary image ({0, 1}^(WxH)) or inferring probability for vessel presence ([0, 1]^(WxH)). This should be clarified.

The purpose of the "Types" section is not clear and may be used in the wrong way.

In A1, more specificity could be provided, such as mentioning a minimum resolution for "High-Quality Input Images".

The meaning of A4:"Stable Operating Environment, RVSS assumes that the software operates in a stable and controlled computing environment." is unclear to me.

Regarding A3 which considers the preprocessing as an assumption contradicts with assuming it's part of the software requirements (R2), too. A3 should be removed.

For the theoretical model’s source, the links provided do not contain the related definitions, such as TM1. It's unclear where these theoretical models were extracted from.

Regarding TM3, the connection to other parts is unclear. Perhaps elaborating on how CNN is used for feature extraction and representation would clarify this. Additionally, it's unclear where the output (S_feature) is utilized.

For GD3, the types of Y_pred and Y_actual are not specified. Additionally, the formulation is limited to Manhattan distance, whereas a more general definition could be provided for distance between two vectors. check this: https://en.wikipedia.org/wiki/Metric_space

In R4, metrics like accuracy are mentioned as the output of the software, but it's important to note that when the system is deployed, access to ground-truth data may not be available. So how will the accuracy be calculated? 
"

**Comment by mirzaim** [comment]
Hi Dr. @smiths.
I believe I already addressed that and mentioned it in the previous post.
<img width="843" alt="image" src="https://github.com/lele0007/Blood-vessel-segmentation/assets/14794797/651f554c-c7df-4ead-ab8a-95e98b2f6b87">

I mention them in this post again:
#15, #16, #17, #18, #19 

If this addresses your concern, please consider closing the issue.

**Comment by smiths** [comment]
Looks good @mirzaim.  You did everything right, except for copying the issues to summarize them.  Your pointers to the issues you created is all that you need.  (I did miss that you did that, partly because there was so much text where I didn't expect to see much text.)  :smile:
