### ISSUE TITLE
VnV Pre-presentation review

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#6]
@smiths  Hi Prof. Smiths, I have uploaded my presentation PPT,  please review it.
[VnV Plan presentation](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/VnVPlan/VnV_presentation.pdf)

**Comment by smiths** [comment]
Feedback:

- for slide 3, if  you made changes to the checklists from "capTemplate" please point that out during your presentation
- I don't understand test-id2.  Is there a correct solution that you are comparing to?
- I don't understand test-id3.  What is the correct behaviour?  What are the inputs?  Please be specific.  This comment also applies for test-id4 and test-id5.  What specifically are the inputs for the test?  You should point to specific files.  What is the expected output?  You should be specific.
- the definition of accuracy looks good, but where are you going to get the true solution from?  Are you using a pseudo-oracle?
- for the usability test you should be more specific.  What image are they uploading?  
- Is the usability survey based on another survey?
- The nonfunctional requirement on performance shouldn't specify an absolute value, as we discussed in class.  I think you can measure performance as part of usability.  You can ask the users about their thoughts on the performance time.  
- You should have plans for describing the performance of your software.  What experiment will you run?  What graphs will you produce?
- You can't really specify unit tests now because you haven't done the design yet

**Comment by smiths** [comment]
@lele0007 an idea you should consider is to construct a test case where you know the answer.  You can make your own image with a known network of vessels and then verify that you recapture that network.  You can manufacture many test cases this way.  You could add noise to the known solution and see the impact of the noise.
